name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

jobs:
  # build:
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: haskell:latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Permissions bug workaround
  #       run: "chown -R $(id -un):$(id -gn) ~"

  #     - name: Build project
  #       run: |
  #         stack build --install-ghc --allow-different-user
  #         stack --local-bin-path build install
  #         mv build/glados-exe glados

  #     - name: Upload project build for the release job
  #       uses: actions/upload-artifact@v1
  #       if: always()
  #       with:
  #         name: glados
  #         path: glados

  update_release_draft:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Create release draft
        id: create_release
        uses: release-drafter/release-drafter@v5.22.0
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tmp prints
        env:
          TMP_STEPS: ${{ toJson(steps) }}
          TMP_RELEASE: ${{ toJson(steps.create_release) }}
          TMP_OUTPUTS: ${{ toJson(steps.create_release.outputs) }}
          TMP_URL: ${{ upload_url }}
        run: |
          echo "$TMP_STEPS"
          echo "---"
          echo "$TMP_RELEASE"
          echo "---"
          echo "$TMP_OUTPUTS"
          echo "---"
          echo "$TMP_URL"

      # - name: Download project build
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: glados

      # - name: zip project build
      #   run: zip glados.zip glados

      # - name: Upload release asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: glados.zip
      #     asset_name: glados.zip
      #     asset_content_type: application/zip